experiment_name: "bert_restoration_capacity"
dataset_name: "wikitext"
dataset_subset: "wikitext-2-raw-v1"
test_split: "validation"
output_file: "results/bert_restoration_results.csv"

device: "cuda" 

lambda_budgets:
  - name: "BERT-base"
    model_id: "bert-base-uncased"
    storage_cost_params: 109482240
  - name: "RoBERTa-base" 
    model_id: "roberta-base"
    storage_cost_params: 124645120
  # - name: "BERT-large" # Can be added for a more comprehensive run
  #   model_id: "bert-large-uncased"
  #   storage_cost_params: 335141888


theta_budgets: [0.1, 0.5, 0.9] 
theta_max: 0.9 
